version: '3.8'

services:
  autos:
    image: ${DOCKER_REGISTRY-}autos
    container_name: autos_api
    build:
      context: .
      dockerfile: autos/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Database=autos;Username=postgres;Password=postgres
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: autos_database
    environment:
      - POSTGRES_DB=autos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
